gateways:
  tangram_duckdb:
    state_connection:
      type: duckdb
      database: local.db
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
      type: tangramsql
      database: duckdb
      engine_type: duckdb
      catalog: iceberg
      host: localhost
      port: 9200
      user: tangram
      password: <your tangram os access token>


  tangram_clickhouse:
    state_connection:
      type: duckdb
      database: local.db
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
      type: tangramsql
      database: clickhouse
      catalog: clickhouse
      engine_type: clickhouse
      host: localhost
      port: 9200
      user: tangram
      password: <your tangram os access token>


    # concurrent_tasks: 1
      # register_comments: True
      # pre_ping: False
      # pretty_sql: False
      # catalogs:
      # extensions:
      # connector_config:
      # token:


default_gateway: tangram_duckdb
gateway_managed_virtual_layer: true


model_defaults:
  dialect: duckdb
  start: 2025-04-25
