gateways:
  tangram_duckdb:
    state_connection:
      type: duckdb # sql mesh state using DuckDB for local demo only
      database: local.db
    connection:
      type: tangramsql
      database: duckdb
      engine_type: duckdb
      catalog: iceberg # catalog set to iceberg, to write the data as Iceberg Tables or Iceberg Views
      host: localhost # Tangram SQL local instance host
      port: 9200 # Tangram SQL local instance port
      user: tangram
      password: #<Tangram OS local instance access token>

  tangram_clickhouse:
    state_connection: # sql mesh state using DuckDB for local demo only
      type: duckdb
      database: local.db
    connection:
      type: tangramsql
      database: clickhouse 
      catalog: clickhouse # ClickHouse catalog in Tangram SQL, use this catalog to create model as ClickHouse Tables or Views
      engine_type: clickhouse
      host: localhost # Tangram SQL local instance host
      port: 9200 # Tangram SQL local instance port
      user: tangram
      password: #<Tangram OS local instance access token>

default_gateway: tangram_duckdb
gateway_managed_virtual_layer: true

model_defaults:
  dialect: duckdb
  start: 2025-04-25
